name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 182061027050.dkr.ecr.us-east-1.amazonaws.com
  ECS_CLUSTER: my-voting-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        service: [vote, worker, result]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ${{ matrix.service }}
          docker build -t $ECR_REGISTRY/${{ matrix.service }}-app:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/${{ matrix.service }}-app:latest .
          docker push $ECR_REGISTRY/${{ matrix.service }}-app:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ matrix.service }}-app:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service ${{ matrix.service }}-app-service --force-new-deployment
